[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded by ^/ will apply only to files and directories
# in the root of the project.
^/build/  # exclude build directory
| ^/dist/  # exclude distribution directory
'''

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]
exclude = [".git", "__pycache__", "build", "dist", "*.egg-info", "venv", "env"]
per-file-ignores = [
    # Test files can have longer lines for readability
    "test_*.py:E501",
    # Legacy files - gradual improvement
    "calibre_control_demo.py:F401"
]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
in-place = true